"ans_bow_size": !!int "1"
"ans_ctx_entity_bow_size": !!int "6"
"ans_enc_dropout": !!float "0.2"
"ans_path_bow_size": !!null "null"
"attention": "add"
"batch_size": !!int "32"
"data_dir": "./data/"
"gpu": !!int "1"
"hidden_size": !!int "128"
"learning_rate": !!float "0.001"
"margin": !!int "1"
"mem_size": !!int "96"
"model_file": "./models/bamnet.md"
"name": "SaaS"
"no_cuda": !!bool "false"
"num_ent_types": !!int "46"
"num_epochs": !!int "1"
"num_hops": !!int "1"
"num_query_words": !!int "10"
"num_relations": !!int "46"
"o_embed_size": !!int "128"
"pre_word2vec": "./data/glove_pretrained_300d_w2v.npy"
"que_enc_dropout": !!float "0.3"
"query_markup_size": !!int "1"
"query_size": !!int "32"
"raw_word2vec": "./glove_pretrained_300d_w2v"
"test_batch_size": !!int "1"
"test_data": "test_vec.json"
"test_margin":
- !!float "0.7"
"train_data": "train_vec.json"
"valid_data": "valid_vec.json"
"valid_patience": !!int "10"
"vocab_embed_size": !!int "300"
"vocab_size": !!int "101139"
"word_emb_dropout": !!float "0.3"
